fix: endurance-tests run sequentially

diff --git a/layers/meta-image-tests/recipes-tests/endurance-tests/files/run-ptest b/layers/meta-image-tests/recipes-tests/endurance-tests/files/run-ptest
--- a/layers/meta-image-tests/recipes-tests/endurance-tests/files/run-ptest
+++ b/layers/meta-image-tests/recipes-tests/endurance-tests/files/run-ptest
@@ -7,25 +7,14 @@ echo "=== Running image ptest ==="
 
 PASS=0
 FAIL=0
-PIDS=()
-TEST_NAMES=()
 
 for test in tests/*/*/*.sh; do
     test_name=$(basename "$test")
     
     echo "START: $test_name"
-    ./"$test" >> "${test}-output" 2>&1 &
-    pid=$!
-    PIDS+=($pid)
-    TEST_NAMES[$pid]=$test_name
-done
+    ./"$test" >> "${test}-output" 2>&1
 
-for pid in "${PIDS[@]}"; do
-    wait $pid
-    result=$?
-    test_name="${TEST_NAMES[$pid]}"
-    
-    if [ $result -eq 0 ]; then
+    if [ $? -eq 0 ]; then
         echo "PASS: $test_name"
         PASS=$((PASS+1))
     else
@@ -34,15 +23,15 @@ for pid in "${PIDS[@]}"; do
     fi
 done
 
-echo "=== Summary: $PASS passed, $FAIL failed ==="
-
 for test in tests/*/*/*.sh; do
     output_file="${test}-output"
     if [ -f "$output_file" ]; then
-        echo "=== Output for $(basename "$test") ==="
+        echo -e "\n=== Output for $(basename "$test") ===\n"
         cat "$output_file"
         rm "$output_file"
     fi
 done
+
+echo "=== Summary: $PASS passed, $FAIL failed ==="
 
 [ $FAIL -eq 0 ] || exit 1
